/// <reference types="vite/client" />

import type { UserCredentials } from 'treasure-trove-shared';

// This interface defines the information that will be returned from a successful login attempt.
export interface AuthInfo {
  token: string;
}

// This interface defines what information about a user can be retrieved from the backend.
export interface UserInfo {
  username: string;
}

// This class defines frontend API methods for the backend database.
class UserApi {
  // Register a new user account, which requires just a username and password.
  // If successful, the username will be returned.
  static async signup({
    username,
    password,
  }: UserCredentials): Promise<{ username: string }> {
    // Send request to create account.
    const res = await fetch(`${import.meta.env.VITE_BACKEND_URL}user/signup`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username, password }),
    });
    if (!res.ok) throw new Error('failed to sign up');
    return await res.json();
  }

  // Log in to an existing user account with a username and password.
  // If successful, the new JWT authentication token generated by the backend will be returned.
  static async login({
    username,
    password,
  }: UserCredentials): Promise<AuthInfo> {
    // Send request to log in.
    const res = await fetch(`${import.meta.env.VITE_BACKEND_URL}user/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username, password }),
    });
    if (!res.ok) throw new Error('failed to log in');
    return await res.json();
  }

  // Retrieve information about a given user.
  // A user's ID is a unique identifier assigned by the backend, which we parse from the JWT token.
  static async getUserInfo(id: string): Promise<UserInfo> {
    const res = await fetch(`${import.meta.env.VITE_BACKEND_URL}users/${id}`, {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
    });
    if (!res.ok) throw new Error('failed to fetch user info');
    return await res.json();
  }
}

export default UserApi;
